### PR TITLE
Search button style changes

### PR DESCRIPTION
**Pull request by blairlierman**
Based on feedback from one of our teams, the Search functionality wasn't easily discovered. 
This update changes the search button to include text along with an icon and to look like one of the other tabs.

fund009

There is also an update to the LESS file to match some earlier CSS changes.

### CODE REVIEW

**Comment by blairlierman** [comment]
Fair enough. Do you have any suggestions that would include better UI/UX, but also make it a little clearer that the search functionality is available?

**Comment by blairlierman** [comment]
My initial idea would be remove the search text and increase the size of the search icon slightly, but leaving it in the same basic location.

Something like this (although with a less aliased icon):
fund010

**Comment by blairlierman** [comment]
@NateOwen I removed the "Search" text, center the icon and pulled in your merged changes.
Now it looks like this:
fund012

Does that fit better with the UI/UX?

**Comment by NateOwen** [comment]
@blairlierman That's better but still not what I'm looking for.  It already currently matches the design Jason gave me so that's all I can suggest.

**Comment by juanzavala** [comment]
@NateOwen Hi Nate, good to virtually connect!  I trust this message finds you well and that you are having productive week .  I'm working with Blair and our Foundation teams to address the design concerns regarding search design.  Our initial intent of the design, is make the search feature intuitive for donors when they visit the site.  Based on feedback we received, our end users were not clear what the search feature was designed to accomplish. We also received feedback that the search option didn't carry the same level of importance as the other WSU Categories/allocations. We are looking for direction on what needs to get done to the search design in order to meet design/branding compliance, while maintaining its purpose in an intuitive way.  Can you share with us your ideas/suggestions on how we move forward?  We appreciate all of your hard work and thank you for all efforts on this project and could not have gotten this far without your expertise.

**Comment by NateOwen** [comment]
@blairlierman @juanzavala Hey Juan, good to hear from you.  Yeah I've been real busy.  I took another look at this pull request and discussed the design with Jason.  Having the search icon stand alone or with the word search beside it should both be intuitive.  Although our recommendation would be to have it stand alone,  after going through different scenarios I don't think there is a right or wrong.  You probably have a better idea  what's best for your user.

**Pull request merged**
