### PR TITLE
Fix auto complete

### PR DESCRIPTION
**Pull request by NateOwen**

### CODE REVIEW

**Comment by NateOwen** [comment]
@blairlierman Take a look and see if this fixes the autocomplete issues

**Comment by blairlierman** [comment]
@NateOwen The styling isn't getting applied to backing list for the autocomplete. It looks like jQuery UI creates a hidden list at the end of the file, outside of the fundSelectionForm div.

When I removed the #fundSelectionForm from the CSS before the .ui-autocomplete elements, the styling worked, but that probably isn't a long term solution.

Style-wise, for now my only feedback would be:
1. Can we remove the bullet from the front of the list items
2. Is it possible to capitalize the list items, so they are consistent with the rest of the drop downs?

**Comment by NateOwen** [comment]
@blairlierman Take a look again please.

**Comment by blairlierman** [comment]
The fixes look good. There was just one more minor issue that I saw. 

The chevron/arrow/speech indicator shows over the top of the search drop down:
wp002

This occurred on Firefox, v50.1.0.

**Comment by jeremyfelt** [comment]
Hmm. I hit the "Update branch" button without thinking. @NateOwen @blairlierman if you make any more changes to this branch, make sure to pull it's current state first. :)

**Comment by NateOwen** [comment]
@blairlierman I don't understand how that could happen.  Can you use inspector and tell me how it's getting those styles?

**Comment by blairlierman** [comment]
@NateOwen It appears the z-index for that element was set to 1 in #fundSelectionForm #selectedFunds li:first-child:after in the CSS. It is set in li:first-child:after on line 379 in the LESS file.

Also, could you remove the "selected" class from the $100 amount button in the includes\class-wsuwp-shortcode-fundselector.php file (on line 150), so nothing is selected by default, since we are now giving the user a choice whenever a fund is selected?

**Comment by blairlierman** [comment]
@NateOwen @jeremyfelt Could one of you #review my updates? 
I made the updates that I suggested in my previous comment as well as adding styling to the new unit fund dropdown.

**Comment by NateOwen** [comment]
@blairlierman sorry I was out yesterday.  It looks good to me.

**Pull request merged**
