### PR TITLE
Other Gift Amount Text and Submission

### PR DESCRIPTION
**Pull request by funkSoRubber**
The text on the add fund button for other gift amounts has been changed from "+ Add Fund" to "Next" to make it more clear that to proceed the button must be pressed. Additionally, if enter is pressed in the field where the other gift amount is typed, the fund will be added to the list.

### CODE REVIEW

**Comment by funkSoRubber** [comment]
@blairlierman Can you take a look at what's failing in Travis CI? I don't get any errors when I run phpcs myself.

**Comment by blairlierman** [comment]
@jeremyfelt Could you help us look into the Travis CI build failure? It appears it can't find grunt.

**Comment by blairlierman** [comment]
@funkSoRubber I think we should have the amount selected by default to make it easier to edit. You should be able to do it by adding something like `	}).focus(function (){
		$(this).select();
	});` to `$("#otherAmount").on('input propertychange paste', function () {`...

**Comment by jeremyfelt** [comment]
@blairlierman Taking a look right now. I'll submit a PR in a few minutes that should take care of it.

**Pull request merged**
